### ISSUE TITLE
Bug in MotionControlHandle.hpp

### ISSUE THREAD

**Issue by YeeCY** [fzi-forschungszentrum-informatik/cartesian_controllers#10]
**Description**

I found a bug in `MotionControlHandle.hpp` about kinematics computation.

https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/87f11cf5a84a7c7223d55928447b396e2e45e8d6/cartesian_controller_handles/include/cartesian_controller_handles/MotionControlHandle.hpp#L163

this function call gives the correct answer, you can check the result of this call

https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/87f11cf5a84a7c7223d55928447b396e2e45e8d6/cartesian_controller_handles/include/cartesian_controller_handles/MotionControlHandle.hpp#L293

It returns 0, which means no error.

However, when we call the `getEndEffectorPose` in the `starting` function again:

https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/87f11cf5a84a7c7223d55928447b396e2e45e8d6/cartesian_controller_handles/include/cartesian_controller_handles/MotionControlHandle.hpp#L70

The `m_fk_solver` returns -4, which means error. In this case, the initial pose of the interactive marker is always at the origin of the base frame.

**Reason**

It is simple because `robot_chain` is a local variable in the `init` function, and it is deleted when the `starting` function is called.

https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/87f11cf5a84a7c7223d55928447b396e2e45e8d6/cartesian_controller_handles/include/cartesian_controller_handles/MotionControlHandle.hpp#L100

**Fix**

Add the `robot_chain` to member variables works!

**Comment by stefanscherzinger** [comment]
Thanks @YeeCY for pointing to this bug. It's fixed in 5e6e23876e3b56bb6d3b36d49fa1d3c96e3a5d0a
