### ISSUE TITLE
Error while cloning this repo

### ISSUE THREAD

**Issue by marioesteban11** [fzi-forschungszentrum-informatik/cartesian_controllers#105]
Hi everyone,

Trying to clone your repository [cartesian controllerss](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers) the terminal says:

´´´
Cloning into 'cartesian_controllers'...
[git@github.com](mailto:git@github.com): Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
´´´

And I dont know if my github is wrongly configurated or i need any permision to clone it

**Comment by stefanscherzinger** [comment]
Hi @marioesteban11 

That's interesting. I haven't heard that before and assume some issue with your ssh configuration. Here's a quick [checklist provided by github](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey). If one of the answers covers your case, you could post your solution here to help other users.

**Comment by stefanscherzinger** [comment]
Please reopen if this still not works for you.
