### ISSUE TITLE
When to use which interface?

### ISSUE THREAD

**Issue by FrederikPlahl** [fzi-forschungszentrum-informatik/cartesian_controllers#11]
Hey there,

I have a question regarding the PositionJointInterface and the VelocityJointInterface. Are there differences in the behavior of the robot when I use the different interfaces or is that just an option for those who have only the PositionJointInterface or only the VelocityJointInterface available for their robot?

I´m currently using the position_controllers/CartesianMotionController in combination with the Universal_Robots_ROS_Driver in a scenario where the end-effector needs to hold a pose while the mobile platform, on which the manipulator is built, is moving. I´m experiencing the end-effector lacking behind the given pose when I´m moving the mobile platform at a higher speed. Are there any chances of improvement in reaction time to the movement when I use the velocity_interface/CartesianMotionController or can I only improve it in changing the PD-Gains?

Thanks for the help!

**Comment by stefanscherzinger** [comment]
HI,

> Are there differences in the behavior of the robot when I use the different interfaces or is that just an option for those who have only the PositionJointInterface or only the VelocityJointInterface available for their robot?

It's more the second: An option, just in case.
The PositionJointInterface has a slightly different functioning, though: The controllers get an additional _iterations_ parameter that allows them to forward simulate various steps before the result of that gets send to the joints. That allows the CartesianMotionController to behave like an Inverse Kinematics (IK) solver. That means if you send it only one distant target pose, it will not interpolate but be there within the next joint configuration. It's crucial in this mode that users interpolate target motion themselves to avoid jumps in joints.

> Are there any chances of improvement in reaction time to the movement when I use the velocity_interface/CartesianMotionController or can I only improve it in changing the PD-Gains?

VelocityJointInterface will not make it faster. Stay on the PositionJointInterface and try increasing both the _error_scale_ and the number of _iterations_.  The internal iterations add more computation overhead, so be sure to build in Release mode. If that's not sufficient for high speeds, then maybe changing the limits of the error_scale is required. I set some values there in the good faith that this should be enough for most use cases. But custom settings might require higher values. The PD gains are more to balance different Cartesian axes.

@FrederikPlahl About how much delay are we talking?
