### ISSUE TITLE
I am a beginner and I want to apply this package to my simulation robotic arm. What should I do

### ISSUE THREAD

**Issue by chouweixin** [fzi-forschungszentrum-informatik/cartesian_controllers#119]
I am a beginner and I want to apply this package to my simulation robotic arm. What should I do

**Comment by stefanscherzinger** [comment]
@chouweixin 

Thanks for your interest in this controller suite. I have a few questions concerning your setup that might help me explain the details better:
- What's your ROS1/2 Version?
- What's your simulator?
- Which robot arm do you plan to use?

**Comment by chouweixin** [comment]
Thank you for your reply，my version is ROS1, the robot arm is ur10,I what to apply this package to my  robotic

**Comment by stefanscherzinger** [comment]
@chouweixin 

Sorry for not responding earlier. Did you manage to set things up in the meantime?
I need more information to help:
- What ROS1 version? (Melodic, Noetic)
- What simulator? (Gazebo classic, Gazebo Garden, ..., or just RViz)

**Comment by chouweixin** [comment]
> @chouweixin
> 
> Sorry for not responding earlier. Did you manage to set things up in the meantime? I need more information to help:
> 
>     * What ROS1 version? (Melodic, Noetic)
> 
>     * What simulator? (Gazebo classic, Gazebo Garden, ..., or just RViz)

thank your very much, the vesion is melodic, I what to simulation in gazebo classic. so could you  give me some suggestions.

**Comment by chouweixin** [comment]
I already know how to do it, thank you for your reply. I wish you smooth work and good health

> > @chouweixin
> > Sorry for not responding earlier. Did you manage to set things up in the meantime? I need more information to help:
> > ```
> > * What ROS1 version? (Melodic, Noetic)
> > 
> > * What simulator? (Gazebo classic, Gazebo Garden, ..., or just RViz)
> > ```
> 
> thank your very much, the vesion is melodic, I what to simulation in gazebo classic. so could you give me some suggestions.

I already know how to do it, thank you for your reply. I wish you smooth work and good health

**Comment by chouweixin** [comment]
> @chouweixin
> 
> I'm happy to hear that it works for you! Could you post your launch file here? That could help others with a similar setup.
Sorry for not responding earlier，I will glad share it once I have organized it

**Comment by ZZWang21** [comment]
@chouweixin hi, did you set up your Gazebo? how did you use the "joint_to_cartesian_controller"? Thank you.

**Comment by chouweixin** [comment]
> @chouweixin hi, did you set up your Gazebo? how did you use the "joint_to_cartesian_controller"? Thank you.

Sorry, I just saw your message, if it is convenient for you, I can send it directly to you

**Comment by qynino** [comment]
> > @chouweixin hi, did you set up your Gazebo? how did you use the "joint_to_cartesian_controller"? Thank you.
> 
> Sorry, I just saw your message, if it is convenient for you, I can send it directly to you

could you share this code for me? I am a beginner

**Comment by Sunday377** [comment]
ok， I can send it to you, how to contact with you



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzi-forschungszentrum-informatik/cartesian_controllers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月23日(星期五) 下午5:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzi-forschungszentrum-informatik/cartesian_controllers] I am a beginner and I want to apply this package to my simulation robotic arm. What should I do (Issue #119)





   
@chouweixin hi, did you set up your Gazebo? how did you use the "joint_to_cartesian_controller"? Thank you.
  
Sorry, I just saw your message, if it is convenient for you, I can send it directly to you
  
could you share this code for me? I am a beginner

**Comment by qynino** [comment]
> ok， I can send it to you, how to contact with you
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fzi-forschungszentrum-informatik/cartesian_controllers" ***@***.***&gt;; 发送时间:&nbsp;2024年2月23日(星期五) 下午5:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [fzi-forschungszentrum-informatik/cartesian_controllers] I am a beginner and I want to apply this package to my simulation robotic arm. What should I do (Issue #119) @chouweixin hi, did you set up your Gazebo? how did you use the "joint_to_cartesian_controller"? Thank you. Sorry, I just saw your message, if it is convenient for you, I can send it directly to you could you share this code for me? I am a beginner — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

thanks for reply, this is my email: ngoc.ngocquy@gmail.com

**Comment by Yeesha-R** [comment]
Hi @qynino and @chouweixin, could you please guide me on how you set up your Gazebo? and how did you use the "joint_to_cartesian_controller"?
If needed, my email is aisraj12000@gmail.com. 
Thanks.
