### ISSUE TITLE
Switch init() method in controller base

### ISSUE THREAD

**Issue by stefanscherzinger** [fzi-forschungszentrum-informatik/cartesian_controllers#13]
**Background**: There's a global request for _/robot_description_ [here][1] that prevents pushing nodes that use this library into namespaces. However, using _robot_description_ instead will make this controller look under its own namespace. I don't like this default, because it will not work out-of-the-box for the many users whose setup works with a global /robot_description.

**Possible solution**: Use [another init() method][2]. This allows both a root node handle and private node handle. So I can have robot_description global per default and the more controller-specific parameters local. 

This should fix #12 

[1]: https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/master/cartesian_controller_base/include/cartesian_controller_base/cartesian_controller_base.hpp#L79
[2]: https://github.com/ros-controls/ros_control/blob/noetic-devel/controller_interface/include/controller_interface/controller.h#L86

**Comment by gavanderhoorn** [comment]
> However, using _robot_description_ instead will make this controller look under its own namespace. I don't like this default, because it will not work out-of-the-box for the many users whose setup works with a global /robot_description.

I believe that's what [ros::param::search(..)](http://wiki.ros.org/roscpp/Overview/Parameter%20Server#Searching_for_Parameter_Keys) is for:

> There are times where you want to get a parameter from the closest namespace. For example, if you have a "robot_name" parameter, you just want to search upwards from your private namespace until you find a matching parameter. Similarly, if you have a group of camera nodes, you may wish to set some parameters commonly in a shared namespace but override others by setting them in a private (~name) namespace.
