### ISSUE TITLE
Using my_cartesian_motion_controller in gazebo, the UR5 joints start to move when activate my_cartesian_motion_controller.

### ISSUE THREAD

**Issue by caimingxue** [fzi-forschungszentrum-informatik/cartesian_controllers#144]
Hello, @fzi-admin. Using my_cartesian_motion_controller in gazebo, the UR5 starts to move when activate my_cartesian_motion_controller. However, I don't send any message. The pose of UR5 do not change. However, some joints are moving. Here is the video.

https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/assets/45029643/52fe0137-358a-4ab9-b783-e670cf603930

**Comment by stefanscherzinger** [comment]
Hi @caimingxue 

Thanks for the video. I can see the drift. Does this happen on the newest *master* branch? What's the output of `git rev-parse HEAD` in a sourced terminal for the `cartesian_controllers`?

**Comment by stefanscherzinger** [comment]
Please reopen if this is still an issue.
