### ISSUE TITLE
'DEPENDS Eigen3' get warning during building

### ISSUE THREAD

**Issue by jsbyysheng** [fzi-forschungszentrum-informatik/cartesian_controllers#17]
I got this warning when building `cartesian_compliance_controller`:
```
catkin_package() DEPENDS on 'Eigen3' but neither 'Eigen3_INCLUDE_DIRS' nor   'Eigen3_LIBRARIES' is defined.
```
This warning is caused by  `cartesian_compliance_controller` 's `CMakeLists.txt` Line 118:
```
DEPENDS Eigen3
```
which should be:
```
DEPENDS EIGEN3
```

To see this warning, you should execute `catkin clean` at first.

**Comment by stefanscherzinger** [comment]
Hi @jsbyysheng 

Thanks for spotting this. I'll have a look.
