### ISSUE TITLE
Using  my_cartesian_force_controller in ur3

### ISSUE THREAD

**Issue by yaogengcheng** [fzi-forschungszentrum-informatik/cartesian_controllers#18]
Hello,
    Now I want to use my_cartesian_force_controller to achieve moving following the trajectory I plan, and at the mean time the end-effector should keep the constant force in the Z axis. I want to use it to finish sanding and polishing by admittance control. How can I do it?
  Thank you!

**Comment by stefanscherzinger** [comment]
Hi @yaogengcheng 

Sorry, this package was somewhat unsupported for the last months. Did you solve your use case?

**Comment by stefanscherzinger** [comment]
@yaogengcheng 

Until I test this myself, you could have a look at [this controller.](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/tree/master/joint_to_cartesian_controller#joint-to-cartesian-controller). The idea is to connect Moveit to the `joint_trajectory_controller` and turn that into a target pose for the `cartesian_compliance_controller`.
