### ISSUE TITLE
using cartesian compliance controller and twist controller in ros noetic

### ISSUE THREAD

**Issue by shrutichakraborty** [fzi-forschungszentrum-informatik/cartesian_controllers#181]
Hello @fmauch ! I would like to use the Cartesian compliance controller with ros1 with the aim of reducing the stiffness of the robot (to make it more compliant). However, I need to be able to send twist message to the robot at the same time. Is this possible? Or can we only use one of the controllers at a time? 

It seems in ros2 for instance, that we cannot use the scaled_joint_trajectory controller at the same time as the motion_controller or force_controller. Is it the same in ros1? 

Thanks!

**Comment by stefanscherzinger** [comment]
@shrutichakraborty 

>  However, I need to be able to send twist message to the robot at the same time. Is this possible? 

Unfortunately, that's not possible at the moment.

> Or can we only use one of the controllers at a time?

Yes, we can only use one _writing_ controller at a time. They send commands to the joint handles and would interfere with commands of other controllers if there wasn't an exclusive ownership.

> It seems in ros2 for instance, that we cannot use the scaled_joint_trajectory controller at the same time as the motion_controller or force_controller

Yes, that's true for ROS1 and ROS2.
There are new mechanisms in ROS2, however, that support _chaning_ different controllers. Unfortunately, I haven't found the time to update the `cartesian_controllers` for this feature..
