### ISSUE TITLE
Unnecessary call to `buildGenericModel` in the forward dynamic solver ?

### ISSUE THREAD

**Issue by captain-yoshi** [fzi-forschungszentrum-informatik/cartesian_controllers#188]
**ROS1 Branch**
I guess this [call](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/ros1/cartesian_controller_base/src/ForwardDynamicsSolver.cpp#L95) is not needed as it is already built in the [init](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/ros1/cartesian_controller_base/src/ForwardDynamicsSolver.cpp#L141) method ? This is recomputed for every control loop.

```cpp
  // ForwardDynamicSolver.cpp
  
  trajectory_msgs::JointTrajectoryPoint ForwardDynamicsSolver::getJointControlCmds(
        ros::Duration period,
        const ctrl::Vector6D& net_force)
  {

    // Compute joint space inertia matrix with actualized link masses
    buildGenericModel();  // Needed ?
    m_jnt_space_inertia_solver->JntToMass(m_current_positions,m_jnt_space_inertia);
    
    ...
    
  }
```

**Comment by stefanscherzinger** [comment]
@captain-yoshi 

Thanks for asking. If I remember correctly, there's a [dynamic parameter](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/82883cb63beb06eb5c09115f996da438f1f65449/cartesian_controller_base/src/ForwardDynamicsSolver.cpp#L215) that influences how responsive the forward simulation behaves that users may change during runtime. The `buildGenericModel()` call should take that into consideration.
