### ISSUE TITLE
/cartesian_motion_controller/current_pose not publishing 

### ISSUE THREAD

**Issue by Yazan-Soliman** [fzi-forschungszentrum-informatik/cartesian_controllers#206]
Hello, 
I am working on a project on a ur10e robot where i have to move it in Cartesian space. 
while it is easy to move the robot to a desired target_frame over /cartesian_motion_controller/target_frame , subscribing to /cartesian_motion_controller/current_pose is not returning any data. I needed this so that the publisher waits until the robot has reached its target.

Thanks in advance!
**Software versions**
 - **ROS version**: Humble

**Comment by leledeyuan00** [comment]
Have you checked the parameter "publish_state_feedback" on configuration yaml file is setted to "on"?

**Comment by Yazan-Soliman** [comment]
@leledeyuan00  actually it is.

```[INFO] [1724062107.393394715] [parameter_lister]:   publish_state_feedback: True```

**Comment by stefanscherzinger** [comment]
@Yazan-Soliman 

That's interesting. I'm not sure about the `[parameter_lister]`, but could you again check the parameter via the controller directly
```bash
ros2 param get /<your-controller-name> solver.publish_state_feedback
```
Note that the topic only gets published once the controller is _active_. 

Additionally, what is the controller's update rate that you are running your setup with? The UR10e should mention that somewhere on the command line output during startup.

**Comment by stefanscherzinger** [comment]
Please re-open if still unclear.
