### ISSUE TITLE
A setup problem with ROS1-Noetic

### ISSUE THREAD

**Issue by clowz1** [fzi-forschungszentrum-informatik/cartesian_controllers#207]
When I run the rosdep command “rosdep install --from-paths ./ --ignore-src -y”， it shows the error that:

ERROR: the following packages/stacks could not have their rosdep keys resolvedto system dependences：XXXXXXX Cannot locate rosdep defintion for [ament_cmake]

I searched this error on the website, it means that I didn't install ament_cmake, but I can't install it with command, please tell me how to solve it, my ros version is noetic, thanks.

**Comment by gavanderhoorn** [comment]
`ament_cmake` is a package used in ROS 2.

Can you make sure you checked out the `ros1` branch of this repository?

**Comment by clowz1** [comment]
Yes，I am sure that I did the command from the ROS1 branch and run these two command “git clone ***@***.***:fzi-forschungszentrum-informatik/cartesian_controllers.git
rosdep install --from-paths ./ --ignore-src -y”




。。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzi-forschungszentrum-informatik/cartesian_controllers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月21日(星期三) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzi-forschungszentrum-informatik/cartesian_controllers] A setup problem with ROS1-Noetic (Issue #207)





 
ament_cmake is a package used in ROS 2.
 
Can you make sure you checked out the ros1 branch of this repository?

**Comment by gavanderhoorn** [comment]
What's the output of `git rev-parse HEAD`? Run it in your clone of this repository.

**Comment by clowz1** [comment]
dc803377752bcbc175004a54985ef011ec4a952




。。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzi-forschungszentrum-informatik/cartesian_controllers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月21日(星期三) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzi-forschungszentrum-informatik/cartesian_controllers] A setup problem with ROS1-Noetic (Issue #207)





 
What's the output of git rev-parse HEAD? Run it in your clone of this repository.

**Comment by gavanderhoorn** [comment]
That's `HEAD` on the `ros2` branch: https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/commit/dc803377752bcbc175004a549485ef011ec4a952.

You need to `git checkout ros1`. Then try again.

**Comment by clowz1** [comment]
Thanks&nbsp;for&nbsp;the&nbsp;reply. I&nbsp;understand what this problem means.


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzi-forschungszentrum-informatik/cartesian_controllers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月21日(星期三) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzi-forschungszentrum-informatik/cartesian_controllers] A setup problem with ROS1-Noetic (Issue #207)





 
That's HEAD on the ros2 branch: dc80337.
 
You need to git checkout ros1. Then try again.

**Comment by stefanscherzinger** [comment]
Thanks @gavanderhoorn for taking care. @clowz1 Please re-open if still unclear.
