### ISSUE TITLE
Failed to load /my_cartesian_compliance_controller/gravity from parameter server

### ISSUE THREAD

**Issue by clowz1** [fzi-forschungszentrum-informatik/cartesian_controllers#211]
Hi, 
    I've tried this controller month ago. At that time I was able to launch '/cartesian_force_controller' and make the manipulator move in the example  "roslaunch cartesian_controller_examples examples.launch". But when I run this code now I receive the following infomation, it means /my_cartesian_compliance_controller/gravity and  /my_cartesian_compliance_controller/tool did not launched, I don't know what's wrong with it.

Thanks

[INFO] [1727233252.478194]: Started controllers: joint_state_controller
[ INFO] [1727233252.482927458]: Forward dynamics solver initialized
[ INFO] [1727233252.482945567]: Forward dynamics solver has control over 6 joints
[ INFO] [1727233252.492928212]: Failed to load /my_cartesian_force_controller/gravity from parameter server
[ INFO] [1727233252.493046146]: Failed to load /my_cartesian_force_controller/tool from parameter server
[ INFO] [1727233252.504736512]: Forward dynamics solver initialized
[ INFO] [1727233252.504759968]: Forward dynamics solver has control over 6 joints
[ INFO] [1727233252.516014589]: Failed to load /my_cartesian_compliance_controller/gravity from parameter server
[ INFO] [1727233252.516249716]: Failed to load /my_cartesian_compliance_controller/tool from parameter server

**Comment by stefanscherzinger** [comment]
I think you can safely ignore those outputs.
They are left-overs from a less-used feature.
