### ISSUE TITLE
Problem of joint limit

### ISSUE THREAD

**Issue by jih189** [fzi-forschungszentrum-informatik/cartesian_controllers#23]
hi @stefanscherzinger, your code is nice to use, and save a lot of my work. But I still want to remind one thing about the joint limit. In some robot, the joint could has no limit, for example Fetch. But in the code, if the urdf file does not provide upper joint limit or lower joint limit, it will consider both of them as zero. Thus, I suggest you can modify it so there will be no joint limit if limit is not provided.

**Comment by stefanscherzinger** [comment]
Hi @jih189
Yes, indeed. _Continuous_ joints [are now supported](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/commit/85420aaeee0afd9eba6b2149c3da1987beb80d55).
