### ISSUE TITLE
Franka Emika Panda and cartesian controllers jerky movements

### ISSUE THREAD

**Issue by fmros** [fzi-forschungszentrum-informatik/cartesian_controllers#5]
Hy there,

did anybody use the cartesian_controllers on Panda Arm before? I am able to get the position_controllers/CartesianMotionController in working correctly, but when moving the interactive marker in rviz and thus generating setpoints, the Panda moves, but makes some cracking noise and jerky movements. It seems that the low-level controllers have some trouble keeping up. The communication of the FCI should be no problem. The robot moves smoothly when planning and moving with moveit. I am working with defaults and ofc tried to tune the error_scale, iterations and pd controller.
It seems though that highering the cut-off frequency of the franka_control_node.yaml from 100 to 1000 makes the issue worse.

Any ideas?

Thanks

**Comment by fmros** [comment]
Can close this by myself, lowering the cut-off frequency of the franka_control_node.yaml to 1 (Hz?) resolves the issue and the controller is working perfectly.

**Comment by YeeCY** [comment]
Another question, how did you configure the URDF for panda? I mean did you use Position transmission in the URDF file for the real robot so that CartesianMotionController can recognize them?
