### ISSUE TITLE
Add example for motion tracking

### ISSUE THREAD

**Issue by stefanscherzinger** [fzi-forschungszentrum-informatik/cartesian_controllers#51]
## Goal
Add a simple python script that shows how to send a moving target to the `cartesian_motion_controller`.

I can also use this to explain the effect of the target sampling rate, and what interpolation features the controller has.
Maybe put that in a integration test.

**Comment by TomGrimwood** [comment]
Hi, do you have any example code for this? Was it ever implemented?

**Comment by stefanscherzinger** [comment]
@TomGrimwood

Maybe a little late for your use case, but there's now a [script](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/master/cartesian_controller_utilities/scripts/pose.py) that turns `geometry_msgs/Twist` into a moving `target_frame`. Here's more [documentation](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/tree/master/cartesian_controller_utilities#motion-control).
