### ISSUE TITLE
How to connect ft sensor to the CartesianForceController

### ISSUE THREAD

**Issue by AbdElRahmanFarhan** [fzi-forschungszentrum-informatik/cartesian_controllers#6]
I have an ati force torque sensor that publishes Wrench messages on a certain topic. My question is. how to let CartesianForceController take that feedback from the sensor to close the control loop.

**Comment by madhan001** [comment]
You need to do a remap from the sensor's wrench topic to the controller's
wrench topic inside the top level launch file of your robot. Use rostopic
list | grep wrench to see all the wrench topics.

**Comment by AbdElRahmanFarhan** [comment]
Thank you for your response. But, what is the name of the controller wrench topic?

**Comment by AbdElRahmanFarhan** [comment]
Thanks I have figured out what is the problem. The ft topic is /your_controller_name/ft_sensor_wrench.

**Comment by madhan001** [comment]
You're welcome, you may close the issue if resolved

**Comment by AbdElRahmanFarhan** [comment]
Solved
