### ISSUE TITLE
How fast cartesian_motion_controller update the commands? How does it interpolate the target?

### ISSUE THREAD

**Issue by AnlageM** [fzi-forschungszentrum-informatik/cartesian_controllers#7]
I'd like to know more about the functioning of `cartesian_motion_controller`. In particular:

- How fast does the controller cycle runs.
      - how fast does it read the target and the current position?
      - how fast does it update the q and q_dot values?

- How is the frequency of target position managed, do you use any interpolation tool?
      - when samples are sparse;
      - when samples are close and at high frequency.

Thank you so much for your attention

**Comment by stefanscherzinger** [comment]
>  - how fast does it read the target and the current position?

The current position is read within every controller manager's update(). This is classically determined by the drivers control cycle. The cartesian_motion_controller will adapt to this scheme. E.g. on URe robots, it will run at 500Hz.

> - how fast does it update the q and q_dot values?

Both q and q_dot values are written to the driver's HW abstraction with the same rate. This happens in the controller manager's write(). This makes sure that the driver's strict time requirements are met.

> How is the frequency of target position managed, do you use any interpolation tool?
> - when samples are sparse;
> - when samples are close and at high frequency.

The cartesian_motion_controller and derived classes (such as the compliance controller) use callbacks to receive their pose targets. Whenever you publish something for them, this new command get's used in the control law. All controllers from this package use simplified forward dynamics simulation on a virtual model as solver. That means they forward simulate a virtual (internal) model to reach the given targets. Users can choose how frequently they want to sample from this simulation and send the intermediate joint configuration to the robot. This gives them the ability to tweak the cartesian_motion_controller between a "one-shot IK solver" (if they send only the final joint state) to an interpolating controller (if they send in between). Users can switch between the two continuously by adjusting[ two parameters](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers#solver-parameters). The first one is an internal control loop, that runs at a factor faster than the driver's control cycle. The second one makes the internal simulation more reactive. May I refer you to the [experiments section D in this paper](https://arxiv.org/pdf/1908.06252.pdf) for an illustration of the interpolation.
