### ISSUE TITLE
Hardware Integration: mapping from cartesian controllers to robot position controllers

### ISSUE THREAD

**Issue by mbs-tahir** [fzi-forschungszentrum-informatik/cartesian_controllers#72]
I am trying to integrate `cartesian_controllers` package to work with [Ufactory XARM6](https://www.ufactory.cc/xarm-collaborative-robot). The arm has a [Robotiq  FT300](https://robotiq.com/products/ft-300-force-torque-sensor) at tool point.

I have got working [PositionController for XARM6](https://github.com/xArm-Developer/xarm_ros/blob/master/xarm_controller/config/xarm6_position_controllers.yaml). Also I have successfully integrated `cartesian_controllers` with XARM6 as described [here](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/issues/47). Controllers are working as expected as described in the README. 

My question is how can I connect XARM6 position controllers with `cartesian_compliance_controller` output? I mean which topic/[ROS interface] should be used to get values from `carteian_controllers` and write them to the topics of position controllers from XARM.

Some relevant information is attached below.

 - **rqt graph**

![rosgraph](https://user-images.githubusercontent.com/100407426/185156026-81316a44-ff56-4b62-9e41-daa466334b33.png)

 - **Information from compliance controller**

![rostopic_list_for_compliance_controller](https://user-images.githubusercontent.com/100407426/185156040-9f7faebc-e997-4e95-95cb-c723ffa37105.png)

 - **xarm position control node**

![xarm_interface_node_info](https://user-images.githubusercontent.com/100407426/185156046-bff66888-08a3-4cc2-a434-c20d62c69298.png)

**Comment by stefanscherzinger** [comment]
Hi @mbs-tahir

> Also I have successfully integrated cartesian_controllers with XARM6 as described https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/issues/47.

I'm happy to hear that! I have, however, some doubts what you mean by *integrated*. You follow-up questions and the rqt graph you posted indicate two completely separate graphs. I assume that you launched the `cartesian_controller`'s example launch file and are now wondering how to connect this to your robot.

It's a little bit different, though. The [position controllers config file](https://github.com/xArm-Developer/xarm_ros/blob/master/xarm_controller/config/xarm6_position_controllers.yaml#L43) that you referenced for your robot seems a good starting point. You could append the configuration for the `my_cartesian_compliance_controller` right into this file below the other controllers and activate the compliance controller online via the controller manager. I like using `rqt` for this. Remember to adjust the `cartesian_compliance_controller`'s configuration to your robot by specifying meaningful links. (That's what I understand by *integrated*)

> I mean which topic/[ROS interface] should be used to get values from carteian_controllers and write them to the topics of position controllers from XARM.

In this setting, the `cartesian_compliance_controller` would *replace* the position controllers from the XARM. Instead of chaining via topics, you start and stop the controllers that you need for a special task. The controller manager will inform you if two controllers are competing for writing to the same joint.

**Comment by mbs-tahir** [comment]
>I'm happy to hear that! I have, however, some doubts what you mean by integrated. You follow-up questions and the rqt graph you posted indicate two completely separate graphs. I assume that you launched the cartesian_controller's example launch file and are now wondering how to connect this to your robot.

Apologies integrate wasn't the write word, but fortunately you guessed it right. I was able to adapt controllers to XARM  from provided example launch files. 

>You could append the configuration for the `my_cartesian_compliance_controller` right into this file below the other controllers and activate the compliance controller online via the controller manager. I like using rqt for this. Remember to adjust the cartesian_compliance_controller's configuration to your robot by specifying meaningful links. (That's what I understand by integrated)

Included `cartesian_controllers` paramters to the `yaml` file and launched the controllers. With updated params from XARM. For simiplicity I have now switched to `cartesian_motion_controllers` just for simplicity in case to move the robot via `InteractiveMarker` provided. I think if this controllers is working with real hardware than others should too. Correct me if I am wrong.

>In this setting, the `cartesian_compliance_controller` would replace the position controllers from the XARM. Instead of chaining via topics, you start and stop the controllers that you need for a special task. The controller manager will inform you if two controllers are competing for writing to the same joint.

I get your point as I was not able to understand how to use these controllers. You guessed it right there was an error while launching both controllers i.e. from `cartesian_controllers` and from `xarm_controllers`. So I had to unload `xarm_controllers` and switch to `cartesian_controllers`

```
[ERROR] [1660810753.715164656]: Could not switch controllers, due to resource conflict
[ERROR] [1660810753.715627]: Failed to start controllers: cartesian_motion_controller, motion_control_handle, joint1_position_controller, joint2_position_controller, joint3_position_controller, joint4_position_controller, joint5_position_controller, joint6_position_controller
```
But still after following all the procedure. The robot didn't move. 
I have tested robot HW node with position controllers and its working(robot moves). I think I need to write/adapt `Robot HW` node to get the robot working right? Can you please share some points on that or on the potential solution? 

Below are some screenshots of the robot and ROS info.

**Controller info**

![controllers_list](https://user-images.githubusercontent.com/100407426/185353939-33f5b3d2-fe14-4eab-bb99-a01d3a1da844.png)

**rqt_graph**

![rosgraph](https://user-images.githubusercontent.com/100407426/185353943-46d1d434-cffa-4e01-b9e0-fb7e0001dda4.png)

**rviz**

![rviz](https://user-images.githubusercontent.com/100407426/185353951-229db973-2be6-44f3-9b17-c9f48090e433.png)

**Comment by mbs-tahir** [comment]
Got things working for the robot. The default provided one `RobotHW` node in `xarm_controllers` worked out of the box. Just had to do some remaps and the real arm is working. Thanks alot to @stefanscherzinger for your time, controllers and help :+1:
