### ISSUE TITLE
How to check the wrench status in the example simulation? 

### ISSUE THREAD

**Issue by ZZWang21** [fzi-forschungszentrum-informatik/cartesian_controllers#93]
Hello experts, 

I have followed the instruction to build the example simulation in RVIZ of the cartesian controller. 

I am starting the my_cartesian_force_controller and set the target_wrench to force.x=2N. 

But I am worndering where I can find the real-time states of the force-torque sensor? I checked all the rostopics, but I found nothing. 

Is it a close loop control? Where can I find the force signal? 

Thank you.

**Comment by stefanscherzinger** [comment]
Hello @ZZWang21 

> But I am worndering where I can find the real-time states of the force-torque sensor?

Those will only be available when working with real hardware. I didn't implement a sensor in simulation yet, although my long-term goal is to have integration testing with controller performance for this.

> Is it a close loop control?

Yes. The idea is that when working on real hardware, users connect their force torque sensor to the controllers' `ft_sensor_wrench` input topic (by remapping). The controllers then try to track the profile given via the `target_wrench` topic.

> Where can I find the force signal?

This will be published by your driver, e.g. I believe it's the `/wrench` topic on *Universal Robots*.
